name: "Dependency Track Github Action"
description: "Handles all dependency track API requests"
author: "Rob Sitro"
inputs:
  url:
    description: "DT URL"
  api_key:
    description: "DT API key"
  project_uuid:
    description: "Project UUID to process"
outputs:
  results:
    description: "Output from the action"
  status:
    description: "Determines if the action failed"
runs:
  using: "docker"
  image: "Dockerfile"
