apps:
  - sample_ruby_app:
      license_file: sample-ruby-app/licenses.json
      dependency_exceptions_file: sample-ruby-app/dependency_exceptions.json
      language: ruby
      dependency_file: sample-ruby-app/Gemfile.lock
block_build: False
allowed_licenses_file: ./allowed_licenses.json