apps:
  - sample_ruby_app:
      license_file: sample-ruby-app/licenses.json
      restricted_licenses_file: sample-ruby-app/restricted_licenses.json
      dependency_exceptions_file: sample-ruby-app/dependency_exceptions.json
      language: ruby
      dependency_file: sample-ruby-app/Gemfile
block_build: True