apps:
  - sample_node_app:
      license_file: sample-node-app/licenses.json
      dependency_exceptions_file: sample-node-app/dependency_exceptions.json
      language: node
      dependency_file: sample-node-app/package-lock.json

block_build: False
allowed_licenses_file: ./allowed_licenses.json