name: License check 

on:
  pull_request: {}
  push:
    branches: ["dev"]
  
jobs:
  licensecheck:
    name: License check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup node
      run: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt install -y nodejs
          source /home/runner/.bashrc
          npm install -g npm@8.5.0
          npm_config_tmp=$RUNNER_TEMP npm install
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: |
        cd sample-node
        gem install license_finder
        license_finder